#define FOSC 12000000          // Frequency of external crystal oscillator
#define CCLK (FOSC*5)          // CPU clock is generated by PLL 
#define PCLK1 (CCLK/4)         // Peripheral clock
#define ADCCLK 3000000         // Required ADC operating clock frequency
#define CLKDIV ((PCLK1/ADCCLK)-1)   // Clock divider value for ADC Used to reduce PCLK to ADC clock
#define CLKDIV_BITS_START 8    // Starting bit position of CLKDIV field in ADCR register
#define PDN_BIT 21             // Power Down bit position in ADCR register
#define CONV_START_BIT 24      // Start conversion bit position in ADCR
#define RESULT_BITS_START 6    // ADC result starts from bit 6 in ADDR register
#define DONE_BIT 31            // DONE bit indicates ADC conversion completed
#define AIN0_0_27  0x00400000  // Configure pin P0.27 as ADC channel AD0.0 input
#define AIN1_0_28	0x01000000   // Configure pin P0.28 as ADC channel AD0.1 input
#define AIN2_0_29	0x04000000  // Configure pin P0.29 as ADC channel AD0.2 input
#define AIN3_0_30	0x10000000  // Configure pin P0.30 as ADC channel AD0.3 input
